// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhook-settings": {
    params: {};
  };
  "/letterboxd": {
    params: {};
  };
  "/auth/plex": {
    params: {};
  };
  "/auth/plex/callback": {
    params: {};
  };
  "/webhook": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhook-settings" | "/letterboxd" | "/auth/plex" | "/auth/plex/callback" | "/webhook";
  };
  "routes/webhook-settings.tsx": {
    id: "routes/webhook-settings";
    page: "/webhook-settings";
  };
  "routes/letterboxd.tsx": {
    id: "routes/letterboxd";
    page: "/letterboxd";
  };
  "routes/auth.plex.tsx": {
    id: "routes/auth.plex";
    page: "/auth/plex" | "/auth/plex/callback";
  };
  "routes/auth.plex.callback.tsx": {
    id: "routes/auth.plex.callback";
    page: "/auth/plex/callback";
  };
  "routes/webhook.tsx": {
    id: "routes/webhook";
    page: "/webhook";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
};